FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY src /app/src
COPY ui /app/ui
COPY scripts /app/scripts
COPY sql /app/sql

ENV PYTHONUNBUFFERED=1
ENV PORT=8080

CMD ["streamlit", "run", "ui/streamlit_app.py", \
     "--server.port=8080", \
     "--server.address=0.0.0.0", \
     "--server.enableXsrfProtection=false", \
     "--server.enableCORS=false", \
     "--server.fileWatcherType=none", \
     "--server.maxUploadSize=50"]

